require 'rake'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  Dir[File.dirname(__FILE__) + '/lib/*.rb'].each { |file| require file }
  #t.pattern = "./spec/**/*_spec.rb" # default
end

task :default => :spec

